export const jobList = [
  {
    "employer_name": "Clevertech",
    "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREroK3iLsY8CwCfpKcCn3hQdZy5Zf_6RvqAoDl&s=0",
    "employer_website": null,
    "employer_company_type": null,
    "job_publisher": "LinkedIn",
    "job_id": "HDOaSf65B98AAAAAAAAAAA==",
    "job_employment_type": "FULLTIME",
    "job_title": "Fullstack Python/React Developer",
    "job_apply_link": "https://www.linkedin.com/jobs/view/fullstack-python-react-developer-at-clevertech-3646506092",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.5554,
    "job_description": "Experience Remote done Right. Over 20 years of remote experience, all 500+ staff are 100% remote and we still grow vibrant relationships, provide exceptional opportunities for career growth while working with stellar clients on ambitious projects\n\nWhat we're working on:\n\nEnterprise companies turn to us to help them launch innovative digital products that interact with hundreds of millions of customers, transactions and data points. The problems we solve every day are real and require creativity, grit and determination. We are building a culture that challenges norms while fostering experimentation and personal growth. In order to grasp the scale of problems we face, ideally, you have some exposure to Logistics, FinTech, Transportation, Insurance, Media or other complex multifactor industries\n\nRequirements\n• 7+ years experience in Python and React\n• Senior-level experience with Javascript, React, Python, and Django\n• Nice to have experience with AgGrid, Bulma, Sass, and React Testing Library\n• Ability to create clean, modern, testable, well-documented code\n• Ideally, you have delivered business-critical software to large enterprises\n• Advanced-level English; ability to clearly communicate complex concepts verbally\n\nStraight from the Devs\n\nWatch short snippets of actual developers (Real, not scripted) share why they joined YouTube Playlist\n\nWhy Clevertech is an amazing place to work at\n\nAt Clevertech, you can expect that you will:\n• Be 100% dedicated to one project at a time so that you can hone your skills, innovate and grow\n• Be a part of a team of talented and friendly senior-level developers\n• Work on projects that allow you to use cutting edge tech. We believe in constantly evolving your mastery\n\nThe result? We produce meaningful work and we are truly proud and excited to be creating waves in an industry under transformation.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687773084,
    "job_posted_at_datetime_utc": "2023-06-26T09:51:24.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=HDOaSf65B98AAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-07-26T09:51:24.000Z",
    "job_offer_expiration_timestamp": 1690365084,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 240,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": null,
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": null,
    "job_max_salary": null,
    "job_salary_currency": null,
    "job_salary_period": null,
    "job_highlights": {
        "Qualifications": [
            "7+ years experience in Python and React",
            "Senior-level experience with Javascript, React, Python, and Django",
            "Nice to have experience with AgGrid, Bulma, Sass, and React Testing Library",
            "Ability to create clean, modern, testable, well-documented code",
            "Ideally, you have delivered business-critical software to large enterprises",
            "Advanced-level English; ability to clearly communicate complex concepts verbally"
        ],
        "Responsibilities": [
            "In order to grasp the scale of problems we face, ideally, you have some exposure to Logistics, FinTech, Transportation, Insurance, Media or other complex multifactor industries"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113300",
    "job_onet_job_zone": "4"
  },
  {
    "employer_name": "Innova Solutions",
    "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP0nwHQFWxAMQ5xGPS35pBl2wyneJMSvl82uSB&s=0",
    "employer_website": "http://www.innovasolutions.co.uk",
    "employer_company_type": null,
    "job_publisher": "LinkedIn",
    "job_id": "a8obPbnHSZYAAAAAAAAAAA==",
    "job_employment_type": "FULLTIME",
    "job_title": "React Developer",
    "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-at-innova-solutions-3644955128",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.5826,
    "job_description": "Innova Solutions is searching for a Frontend React Developer\n\nPosition type: Full-time, Direct Hire with my client\n\nLocation: Remote\n\nAs a React Developer you will be :\n• Developing the latest user-facing features using React\n• Designing a modern highly responsive web-based user interface\n• Building reusable components and front-end libraries for future use\n• Translating designs and wireframes into high-quality code\n• Developing RIA/SPA client application for consuming RESTful APIs\n• Optimizing components for maximum performance across a vast array of web-capable devices and browsers\n• Coordinating with various teams working on distinct layers (user experience designers, other software developers, business stakeholders, quality assurance, etc.)\n• Following Software Development Lifecycle process for software version control, development, testing, and deployment\n• Using modern React testing framework(s) to demonstrate working software that adheres to requirements\n\nThe ideal candidate will have:\n• Strong proficiency in JavaScript and TypeScript (and the relationship between the two)\n• Thorough understanding of React and its principles\n• Understanding HTML and JSX (and the relationship between the two)\n• Understanding CSS and CSS-in-JS and how to create thematic styles for reusability\n• Good understanding of Object-Oriented Programming (OOP) principles and how to apply them to TypeScript classes (and the differences between JS’s prototypical inheritance).\n• Familiarity with modern front-end build pipelines and tools\n• Familiarity with cloud providers (AWS, Azure, Google Cloud Platform) and deployment strategies\n• Familiarity with containerization (Docker), and microservices architecture\n• Experience with common front-end development tools such as Babel, Webpack, NPM, etc.\n• Ability to understand business requirements and translate them into technical requirements\n• A knack for benchmarking and optimization\n• Prior experience with popular React.js workflows (such as Flux or Redux)\n• Familiarity with RESTful APIs, self-describing APIs, Swagger/OpenAPI specifications,\n• XML, JSON, Protocol Buffers, or other common data-serialization strategies\n• Git or other distributed version control systems (familiarity with branching, merging, commits, pushing/pulling, other common operations)\n• Familiarity with code collaboration platforms such as Bitbucket, Gitlab, or Github and submitting/reviewing/approving Pull Requests/Merge Requests.\n• Knowledge of modern authorization mechanisms, such as JSON Web Token, OAuth flows, or common third-party Identity Providers or Social Auth schemes\n\nQualified candidates should APPLY NOW for immediate consideration! Please hit APPLY to provide the required information, and we will be back in touch as soon as possible.\n\nWe are currently interviewing to fill this and other similar positions. If this role is not a fit for you, we do offer a referral bonus program for referrals that we successfully place with our clients, subject to program guidelines. ASK ME HOW.\n\nThank you!\n\nMichael Aguilar\n\nLead Technical Recruiter\n\nmichael.aguilar@innovasolutions.com\n\nPAY RANGE AND BENEFITS:\n\nPay Range*: Between $90,000 - $125,00 per year\n• Pay range offered to a successful candidate will be based on several factors, including the candidate's education, work experience, work location, specific job duties, certifications, etc.\n\nBenefits: Innova Solutions offers benefits( based on eligibility) that include the following: Medical & pharmacy coverage, Dental/vision insurance, 401(k), Health saving account (HSA) and Flexible spending account (FSA), Life Insurance, Pet Insurance, Short term and Long term Disability, Accident & Critical illness coverage, Pre-paid legal & ID theft protection, Sick time, and other types of paid leaves (as required by law), Employee Assistance Program (EAP).\n\nABOUT INNOVA SOLUTIONS: Founded in 1998 and headquartered in Atlanta, Georgia, Innova Solutions employs approximately 50,000 professionals worldwide and reports an annual revenue approaching $3 Billion. Through our global delivery centers across North America, Asia, and Europe, we deliver strategic technology and business transformation solutions to our clients, enabling them to operate as leaders within their fields.\n• Recent Recognitions:One of Largest IT Consulting Staffing firms in the USA – Recognized as #4 by Staffing Industry Analysts (SIA 2022)\n• ClearlyRated® Client Diamond Award Winner (2020)\n• One of the Largest Certified MBE Companies in the NMSDC Network (2022)\n• Advanced Tier Services partner with AWS and Gold with MS\n\nWebsite: https://www.innovasolutions.com/\n\nInnova Solutions is an Equal Opportunity Employer and prohibits any kind of unlawful discrimination and harassment. Innova Solutions is committed to the principle of equal employment opportunity for all employees and to providing employees with a work environment free of discrimination and harassment on the basis of race, color, religion or belief, national origin, citizenship, social or ethnic origin, sex, age, physical or mental disability, veteran status, marital status, domestic partner status, sexual orientation, or any other status protected by the statutes, rules, and regulations in the locations where it operates. If you are an individual with a disability and need a reasonable accommodation to assist with your job search or application for employment, please contact us at hr@innovasolutions.com or (770) 493-5588. Please indicate the specifics of the assistance needed. Innova Solutions encourages all interested and qualified candidates to apply for employment opportunities. Innova Solutions (HireGenics/Volt) does not discriminate against applicants based on citizenship status, immigration status, or national origin, in accordance with 8 U.S.C. § 1324b.\n\nThe company will consider for employment qualified applicants with arrest and conviction records in a manner that complies with the San Francisco Fair Chance Ordinance, the Los Angeles Fair Chance Initiative for Hiring Ordinance, and other applicable laws.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687791813,
    "job_posted_at_datetime_utc": "2023-06-26T15:03:33.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": [
        "paid_time_off",
        "health_insurance",
        "dental_coverage",
        "retirement_savings"
    ],
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=a8obPbnHSZYAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-07-26T15:03:32.000Z",
    "job_offer_expiration_timestamp": 1690383812,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": null,
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": true
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": 90000,
    "job_max_salary": 125000,
    "job_salary_currency": "USD",
    "job_salary_period": "YEAR",
    "job_highlights": {
        "Qualifications": [
            "Using modern React testing framework(s) to demonstrate working software that adheres to requirements",
            "Strong proficiency in JavaScript and TypeScript (and the relationship between the two)",
            "Thorough understanding of React and its principles",
            "Understanding HTML and JSX (and the relationship between the two)",
            "Good understanding of Object-Oriented Programming (OOP) principles and how to apply them to TypeScript classes (and the differences between JS’s prototypical inheritance)",
            "Familiarity with modern front-end build pipelines and tools",
            "Familiarity with cloud providers (AWS, Azure, Google Cloud Platform) and deployment strategies",
            "Familiarity with containerization (Docker), and microservices architecture",
            "Experience with common front-end development tools such as Babel, Webpack, NPM, etc",
            "Ability to understand business requirements and translate them into technical requirements",
            "A knack for benchmarking and optimization",
            "Prior experience with popular React.js workflows (such as Flux or Redux)",
            "Familiarity with RESTful APIs, self-describing APIs, Swagger/OpenAPI specifications,",
            "XML, JSON, Protocol Buffers, or other common data-serialization strategies",
            "Git or other distributed version control systems (familiarity with branching, merging, commits, pushing/pulling, other common operations)",
            "Familiarity with code collaboration platforms such as Bitbucket, Gitlab, or Github and submitting/reviewing/approving Pull Requests/Merge Requests",
            "Knowledge of modern authorization mechanisms, such as JSON Web Token, OAuth flows, or common third-party Identity Providers or Social Auth schemes"
        ],
        "Responsibilities": [
            "Designing a modern highly responsive web-based user interface",
            "Building reusable components and front-end libraries for future use",
            "Translating designs and wireframes into high-quality code",
            "Developing RIA/SPA client application for consuming RESTful APIs",
            "Optimizing components for maximum performance across a vast array of web-capable devices and browsers",
            "Coordinating with various teams working on distinct layers (user experience designers, other software developers, business stakeholders, quality assurance, etc.)",
            "Understanding CSS and CSS-in-JS and how to create thematic styles for reusability"
        ],
        "Benefits": [
            "Pay Range*: Between $90,000 - $125,00 per year",
            "Pay range offered to a successful candidate will be based on several factors, including the candidate's education, work experience, work location, specific job duties, certifications, etc",
            "Benefits: Innova Solutions offers benefits( based on eligibility) that include the following: Medical & pharmacy coverage, Dental/vision insurance, 401(k), Health saving account (HSA) and Flexible spending account (FSA), Life Insurance, Pet Insurance, Short term and Long term Disability, Accident & Critical illness coverage, Pre-paid legal & ID theft protection, Sick time, and other types of paid leaves (as required by law), Employee Assistance Program (EAP)",
            "ABOUT INNOVA SOLUTIONS: Founded in 1998 and headquartered in Atlanta, Georgia, Innova Solutions employs approximately 50,000 professionals worldwide and reports an annual revenue approaching $3 Billion"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3"
  },
  {
    "employer_name": "Thoughtwave Software and Solutions",
    "employer_logo": null,
    "employer_website": null,
    "employer_company_type": null,
    "job_publisher": "Dice",
    "job_id": "vX-2adnsdXIAAAAAAAAAAA==",
    "job_employment_type": "PARTTIME",
    "job_title": "React Developer",
    "job_apply_link": "https://www.dice.com/job-detail/e63513a3-19f7-4c55-ab87-d4f36793ba7e",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.5433,
    "job_description": "Role:React.JS Developer\nLocation:Charlotte, NC (onsite twice a week)\nDuration:6-24 months to perm\n\nMust have:\njust 5 years experience and react.js experience, javascript, and html/css, thats it!\n\nRequired Skills:\n5 years hands on experience (Analysis, design, development, testing and delivery of application software) for web applications with React Js expertise.\nStrong knowledge on ReactJS, CSS and other UI tech stack like micro front end, cloud etc\nStrong JavaScript proficiency\nCSS, HTML, JavaScript expertise\nResponsive design knowledge\nUI/UX experience\nExperience integrating front-end with back-end services\nBuild new, reusable React.js components and front-end libraries and optimize them for maximum performance\nCustomize and fix defects with existing React.js components\nTranslate mockups and wireframes into new user-facing features using React.js\nPerform unit testing\nEnhance the applications front-end framework\nProvide front end development and React.js subject matter expertise\nExperience developing RESTful API services in an enterprise environment using .NET Core 6 / Java.\nExperience with Scrum/Agile\nExperience developing applications in a CI/CD pipeline using tools like Jenkins, GitHub Actions, or Gitlab.\nStrong expertise in working with Node, WebPack and other tools related to React Front End Development\n\n--\nBhargavi Ankam\nIT Recruiter\nStaffing | Thoughtwave Software and Solutions Limited\n\n314 N. Lake St, Suite 6, Aurora IL 60506",
    "job_is_remote": false,
    "job_posted_at_timestamp": 1687789492,
    "job_posted_at_datetime_utc": "2023-06-26T14:24:52.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=vX-2adnsdXIAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-07-27T14:24:52.000Z",
    "job_offer_expiration_timestamp": 1690467892,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": [
        "react.js experience",
        "javascript",
        "HTML",
        "CSS"
    ],
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": null,
    "job_max_salary": null,
    "job_salary_currency": null,
    "job_salary_period": null,
    "job_highlights": {
        "Qualifications": [
            "just 5 years experience and react.js experience, javascript, and html/css, thats it!",
            "5 years hands on experience (Analysis, design, development, testing and delivery of application software) for web applications with React Js expertise",
            "Strong knowledge on ReactJS, CSS and other UI tech stack like micro front end, cloud etc",
            "Strong JavaScript proficiency",
            "CSS, HTML, JavaScript expertise",
            "Responsive design knowledge",
            "UI/UX experience",
            "Experience integrating front-end with back-end services",
            "Experience developing RESTful API services in an enterprise environment using .NET Core 6 / Java",
            "Experience with Scrum/Agile",
            "Experience developing applications in a CI/CD pipeline using tools like Jenkins, GitHub Actions, or Gitlab",
            "Strong expertise in working with Node, WebPack and other tools related to React Front End Development"
        ],
        "Responsibilities": [
            "Build new, reusable React.js components and front-end libraries and optimize them for maximum performance",
            "Customize and fix defects with existing React.js components",
            "Translate mockups and wireframes into new user-facing features using React.js",
            "Perform unit testing",
            "Enhance the applications front-end framework"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3"
  },
  {
    "employer_name": "Rework IT Development",
    "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRygkWgtoBaj5P-zKh_SmkffPP6vySFjIMf26W1&s=0",
    "employer_website": null,
    "employer_company_type": null,
    "job_publisher": "Wellfound",
    "job_id": "oP2eWfICitcAAAAAAAAAAA==",
    "job_employment_type": "FULLTIME",
    "job_title": "React Developer",
    "job_apply_link": "https://wellfound.com/company/rework-it-development/jobs/2716559-react-developer",
    "job_apply_is_direct": true,
    "job_apply_quality_score": 0.583,
    "job_description": "We have an exciting opportunity for a skilled and experienced React Developer to work remote with one of our esteemed clients in the financial sector. As a React Developer, you will collaborate with the customer's team and work closely with our internal development team to deliver top-notch solutions.\n\nResponsibilities:\n• Collaborate with the customer's team to understand their requirements and translate them into technical specifications.\n• Design, develop, and maintain efficient and high-quality web applications using React.js.\n• Ensure the best possible performance, responsiveness, and scalability of the applications.\n• Build reusable components and front-end libraries for future use.\n• Integrate frontend interfaces with server-side logic in collaboration with backend developers.\n• Conduct thorough testing and debugging to identify and fix any issues or bugs.\n• Stay up to date with the latest industry trends, technologies, and best practices.\n\nRequirements:\n• Minimum of 3 years of professional experience as a React Developer.\n• Proficient understanding of web markup, including HTML5 and CSS3.\n• Strong proficiency in JavaScript and TypeScript.\n• Experience with React.js and its core principles.\n• Knowledge of RESTful APIs and asynchronous request handling.\n• Understanding of code versioning tools, such as Git.\n• Strong problem-solving and debugging skills.\n• Excellent teamwork and communication skills.\n• Ability to work in a fast-paced environment and meet project deadlines.\n\nSalary and Benefits:\n• The base salary for this position is $2,750 USD per month.\n• Opportunities for professional growth and career development.\n• Collaborative and inclusive work environment.\n• Exposure to cutting-edge technologies and challenging projects.\n\nPlease include the following information when submitting your application:\n• You have ability to communicate effectively in English?\n• Briefly explain the difference between sync and async in JavaScript (in a few words)?\n\nBonus task: Please perform a Google search for \"staff augmentation in Delaware\" and click on the result from Rework IT Development. Please provide the URL of the page you landed on and mention the page where you found our website.\n\nWe are an equal opportunity employer and value diversity in our team. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, or any other characteristic protected by law.\n\nRework IT Development focuses on Web Development and Website. Their company has offices in Delaware. They have a mid-size team that's between 51-200 employees.\n\nYou can view their website at https://reworkdevs.com/ or find them on LinkedIn.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687546727,
    "job_posted_at_datetime_utc": "2023-06-23T18:58:47.000Z",
    "job_city": "Comitán de Domínguez",
    "job_state": "Chis.",
    "job_country": "MX",
    "job_latitude": 16.22996,
    "job_longitude": -92.11557,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=oP2eWfICitcAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-09-26T06:40:01.000Z",
    "job_offer_expiration_timestamp": 1695710401,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 36,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": null,
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": 33000,
    "job_max_salary": 33000,
    "job_salary_currency": "USD",
    "job_salary_period": "YEAR",
    "job_highlights": {},
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3"
  },
  {
    "employer_name": "Brooksource",
    "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwkNEKYgaXW907fY4mzINAtEvAQGJBQcYdR3th&s=0",
    "employer_website": null,
    "employer_company_type": null,
    "job_publisher": "LinkedIn",
    "job_id": "35-8NLEs4MoAAAAAAAAAAA==",
    "job_employment_type": "CONTRACTOR",
    "job_title": "React Native Developer",
    "job_apply_link": "https://www.linkedin.com/jobs/view/react-native-developer-at-brooksource-3641592944",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.5477,
    "job_description": "React Native Developer\n\n100% Remote\n\nW2 Contract (Option to Hire)\n\nDo you see your next career move taking you to a Fortune 50 healthcare company? Do you aspire to work in a dynamic, high-energy, agile environment? If you feel these words describe your ideal career opportunity, we may have the position for you!\n\nThis client's Customer Experience Management team focuses on building mobile applications that simplify healthcare for its members and providers. They are needing to add a Sr. React Native to assist their team with establishing an unmatched mobile experience across all digital platforms with a focus around customer engagement, proactivity, and personalization during the customer benefit selection.\n\nThis will include working alongside the counterpart Web Development team, as well as user groups to solve business problems and maintain a strong understanding of industry standards in the digital space. You'll also be working closely with multiple Full Stack Engineering teams.\n\nThe tech stack for this group is React Native. This role will require you to have strong React Native experience, preferably previous experience migrating Android and iOS native applications to ReactNative. You will be responsible for providing guidance and thought leadership to the team. The team is a distributed onshore team that operates remotely, working Eastern Standard Time hours.\n\nRequired Qualifications\n• 5+ years of professional experience as Software Engineer or a Full-Stack Developer\n• 3+ years of demonstrable experience building software systems and solutions with React Native\n• 3+ years of experience with Node.JS or GraphQL\n• Strong analytical and reasoning skills with an ability to visualize processes and outcomes.\n• Proficiency in troubleshooting software issues and debugging complex codebase.\n• Deep understanding of agile principles and how they can be flexibly applied\n• Outstanding all-round communication skills and ability to work collaboratively\n• All-hands on deck contributor\n\nPreferred Qualification\n• A passion for solving problems and providing workable solutions\n• Experience working on cross-functional/balanced product development teams\n• Experience with human-centered design approach\n• Healthcare business experience\n• Experience working with remote distributed teams\n\nABOUT EIGHT ELEVEN:\n\nAt Eight Eleven, our business is people. Relationships are at the center of what we do. A successful partnership is only as strong as the relationship built. We’re your trusted partner for IT hiring, recruiting and staffing needs.\n\nFor over 16 years, Eight Eleven has established and maintained relationships that are designed to meet your IT staffing needs. Whether it’s contract, contract-to-hire, or permanent placement work, we customize our search based upon your company's unique initiatives, culture and technologies. With our national team of recruiters placed at 21 major hubs around the nation, Eight Eleven finds the people best-suited for your business. When you work with us, we work with you. That’s the Eight Eleven promise.\n\nEight Eleven Group provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, national origin, age, sex, citizenship, disability, genetic information, gender, sexual orientation, gender identity, marital status, amnesty or status as a covered veteran in accordance with applicable federal, state, and local laws.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687805055,
    "job_posted_at_datetime_utc": "2023-06-26T18:44:15.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=35-8NLEs4MoAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-07-26T18:44:15.000Z",
    "job_offer_expiration_timestamp": 1690397055,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": null,
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": 70,
    "job_max_salary": 75,
    "job_salary_currency": "USD",
    "job_salary_period": "HOUR",
    "job_highlights": {
        "Qualifications": [
            "This role will require you to have strong React Native experience, preferably previous experience migrating Android and iOS native applications to ReactNative",
            "5+ years of professional experience as Software Engineer or a Full-Stack Developer",
            "3+ years of demonstrable experience building software systems and solutions with React Native",
            "3+ years of experience with Node.JS or GraphQL",
            "Strong analytical and reasoning skills with an ability to visualize processes and outcomes",
            "Proficiency in troubleshooting software issues and debugging complex codebase",
            "Deep understanding of agile principles and how they can be flexibly applied",
            "Outstanding all-round communication skills and ability to work collaboratively",
            "All-hands on deck contributor"
        ],
        "Responsibilities": [
            "React Native to assist their team with establishing an unmatched mobile experience across all digital platforms with a focus around customer engagement, proactivity, and personalization during the customer benefit selection",
            "This will include working alongside the counterpart Web Development team, as well as user groups to solve business problems and maintain a strong understanding of industry standards in the digital space",
            "You'll also be working closely with multiple Full Stack Engineering teams",
            "You will be responsible for providing guidance and thought leadership to the team",
            "The team is a distributed onshore team that operates remotely, working Eastern Standard Time hours"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113200",
    "job_onet_job_zone": "4"
  },
  {
    "employer_name": "Seneca Resources",
    "employer_logo": "https://media.licdn.com/dms/image/C4D0BAQHPiIdT8Y4Oyw/company-logo_200_200/0/1600362787589?e=2147483647&v=beta&t=WWKlgDG9VKddDH5xOFXSznLwO_4_tcUMs7UU3CDeOYI",
    "employer_website": "http://senecahq.com",
    "employer_company_type": null,
    "job_publisher": "LinkedIn",
    "job_id": "GJC1rxqaS_4AAAAAAAAAAA==",
    "job_employment_type": "FULLTIME",
    "job_title": "React Developer (Full Stack)",
    "job_apply_link": "https://www.linkedin.com/jobs/view/react-developer-full-stack-at-seneca-resources-3643968217",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.5884,
    "job_description": "Our client is a rapidly growing, entrepreneurial, multi-faceted consulting company is seeking a Full Stack React developer to support a federal government entity. They are looking to add an independent, energetic, and self-motivated React developer to an established team working on a federal government project. It’s a small team of developers with support from matrixed staff in other roles. They look for someone who loves to learn and is passionate about keeping up to date with industry trends and technology.\n\nThis developer will participate in building and modernizing web-based applications to support our projects, work with technical leads to develop and enforce standards, collaborate with a development team, and follow solutions as they are developed through production deployment. The team performs custom software development to modernize siloed, legacy applications using modular design standards. The team works closely with clients and other contractors to ensure the performance and reliability of public-facing, mission-critical applications.\n\nWhat you’ll be doing:\n• Identifies requirements by establishing personal rapport with potential and actual clients and with other persons in a position to understand service requirements\n• Develops and maintains applications and databases by evaluating client needs; analyzing requirements; developing software systems\n• Bug fixing, browser testing, accessibility testing\n• Documenting code and processes\n• Collaborate with designers, developers, and project managers on client work\n• Communicating with co-workers about your projects and tasks\n• Actively participate in project discussions and team meetings (e.g., daily standups, code reviews)\n\nMinimum Qualifications:\n• BS in computer science or related field\n• 3+ years of experience building full-stack applications using JavaScript technologies\n• 3+ years of experience with React development\n• Ability to obtain and maintain a Public Trust\n\nPreferred Qualifications:\n• Experience with Node.js\n• Experience with GraphQL\n• Experience with Cloud architecture such as AWS\n• Proficient with Git and GitHub\n• Highly proficient in HTML 5, CSS 3.0, JavaScript, REST Concepts, JWT\n• Proficient understanding of cross-browser compatibility issues and ways to work around them\n\nTechnologies/tools you’ll use:\n• AWS services (S3, CloudFront, Lambda, API Gateway, RDS)\n• GitHub\n• MySQL\n• React\n• Node.js\n• GraphQL/Rest\n• JavaScript, HTML, CSS\n• Gatsby\n• Knex.js\n• Cypress",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687532447,
    "job_posted_at_datetime_utc": "2023-06-23T15:00:47.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=GJC1rxqaS_4AAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-07-23T15:00:47.000Z",
    "job_offer_expiration_timestamp": 1690124447,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 36,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": null,
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": true,
        "degree_preferred": true,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": null,
    "job_max_salary": null,
    "job_salary_currency": null,
    "job_salary_period": null,
    "job_highlights": {
        "Qualifications": [
            "They look for someone who loves to learn and is passionate about keeping up to date with industry trends and technology",
            "BS in computer science or related field",
            "3+ years of experience building full-stack applications using JavaScript technologies",
            "3+ years of experience with React development",
            "Ability to obtain and maintain a Public Trust",
            "AWS services (S3, CloudFront, Lambda, API Gateway, RDS)",
            "MySQL",
            "Node.js",
            "GraphQL/Rest",
            "JavaScript, HTML, CSS"
        ],
        "Responsibilities": [
            "This developer will participate in building and modernizing web-based applications to support our projects, work with technical leads to develop and enforce standards, collaborate with a development team, and follow solutions as they are developed through production deployment",
            "The team performs custom software development to modernize siloed, legacy applications using modular design standards",
            "The team works closely with clients and other contractors to ensure the performance and reliability of public-facing, mission-critical applications",
            "Identifies requirements by establishing personal rapport with potential and actual clients and with other persons in a position to understand service requirements",
            "Develops and maintains applications and databases by evaluating client needs; analyzing requirements; developing software systems",
            "Bug fixing, browser testing, accessibility testing",
            "Documenting code and processes",
            "Collaborate with designers, developers, and project managers on client work",
            "Communicating with co-workers about your projects and tasks",
            "Actively participate in project discussions and team meetings (e.g., daily standups, code reviews)"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113300",
    "job_onet_job_zone": "4"
  },
  {
    "employer_name": "Upwork",
    "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
    "employer_website": "http://www.elance.com",
    "employer_company_type": "Computer Services",
    "job_publisher": "Upwork",
    "job_id": "rCymTWnLmGMAAAAAAAAAAA==",
    "job_employment_type": "CONTRACTOR",
    "job_title": "React developer for medical startup - Contract to Hire",
    "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/React-developer-for-medical-startup_~013de2a664b36010ac/",
    "job_apply_is_direct": true,
    "job_apply_quality_score": 0.6813,
    "job_description": "Hi! We are a small healthcare startup trying to improve workflows for doctors.\n\nWe need an expert React developer who will be in charge of the frontend development, including creating the necessary structures to ensure good code quality.\n\nThe user will be lead through input forms with complex visibility rules for components.\n\nWe have a designer in the team already who creates Figma designs, and a functional backend.\n\nIt would be great to work with someone who is passionate about their work and delivering a great product with a great use-case! Our team is super driven and good and fast communication is a must!\n\nYou should be an expert in React both in terms of rigorous code quality as well as creative design.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687783012,
    "job_posted_at_datetime_utc": "2023-06-26T12:36:52.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=rCymTWnLmGMAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": null,
    "job_offer_expiration_timestamp": null,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": false,
        "experience_preferred": false
    },
    "job_required_skills": [
        "Tailwind CSS",
        "MUI",
        "Redux",
        "TypeScript",
        "React",
        "JavaScript",
        "CSS",
        "HTML",
        "Mobx",
        "Jest"
    ],
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": 25,
    "job_max_salary": 50,
    "job_salary_currency": "USD",
    "job_salary_period": "HOUR",
    "job_highlights": {
        "Qualifications": [
            "It would be great to work with someone who is passionate about their work and delivering a great product with a great use-case!",
            "Our team is super driven and good and fast communication is a must!",
            "You should be an expert in React both in terms of rigorous code quality as well as creative design"
        ],
        "Responsibilities": [
            "We need an expert React developer who will be in charge of the frontend development, including creating the necessary structures to ensure good code quality",
            "The user will be lead through input forms with complex visibility rules for components"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3",
    "job_naics_code": "541511",
    "job_naics_name": "Custom Computer Programming Services"
  },
  {
    "employer_name": "Bass Pro Shops, Bass Pro Shops",
    "employer_logo": "https://upload.wikimedia.org/wikipedia/en/5/5b/Bass_Pro_Shops_logo.png",
    "employer_website": "http://www.basspro.com",
    "employer_company_type": "Retail",
    "job_publisher": "Bass Pro Shops Jobs",
    "job_id": "pF4M_gBZl9kAAAAAAAAAAA==",
    "job_employment_type": "FULLTIME",
    "job_title": "Frontend React Dev 3",
    "job_apply_link": "https://careers.basspro.com/us/en/job/R137768/Frontend-React-Dev-3",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.8054,
    "job_description": "Frontend React Developer will be a member of Digital Commerce team responsible for developing and supporting eCommerce capabilities on multiple brand websites. As part of a dynamic team with growing demand, this role will be responsible for requirement gathering, developing & testing website related enhancements, as well as troubleshooting and remediating issues within the application. This includes support for end-to-end application testing, understanding of integrations to upstream/downstream systems, and adhering to code management activities within an agile framework. This role will work with on/offshore dev team members in supporting and delivering solutions.\n\nRequired Skills & Experience\n• 3+ years hands-on experience in developing and minimum 2 years’ experience with React or other JS based technologies\n• BS degree in Computer Science or related field\n• Solid understanding of web technologies, including HTML, CSS3, and JavaScript\n• Ability to integrate 3rd party APIs and a strong understanding of REST and other API patterns\n• Experience working on NodeJS, ReactJS, Angular, Bootstrap, Typescript\n• Experience with state management like Redux, React-Context, Recoil or similar library\n• Knowledge on JavaScript ES6 features such as classes, arrow functions, string templates, rest/spread operators, promises, async/await\n• Familiar with building responsive layouts using CSS and its compiler workflows (e.g. LESS, SASS/SCSS, styled components).\n• Strong understanding of CS fundamentals, Object Oriented Design and Data Structures\n• Strong troubleshooting and problem-solving skills, strong interpersonal, verbal, and written communication skills, strong relationship builder in cross-functional teams.\n• Experience building, optimizing, and maintaining websites with high traffic and performance demands\n• Familiarity using SVN/GIT/Bitbucket for source code management and Atlassian tools Jira and Confluence.\n\nPreferred Skills & Experience\n• Experience working in a Retail eCommerce environment\n• Familiarity with front-end build tools, such as Webpack, Grunt and Gulp.js\n• Good understanding of asynchronous, closure, event-driven programming\n• Understanding of web accessibility principles, patterns, and testing\n• Worked on design systems building highly composable, reusable components\n• Experience translating design mockups and prototypes into working application designs.\n• Have a great attitude and fit in a fun team and collaborative environment\n• Excited about technology and strong interest in learning latest technologies\n\nEqual Opportunity Employer\n\nBass Pro Shops is an equal opportunity employer. Hiring decisions are administered without regard to race, color, creed, religion, sex, pregnancy, sexual orientation, gender identity, age, national origin, ancestry, citizenship status, disability, veteran status, genetic information, or any other basis protected by applicable federal, state or local law.\n\nReasonable Accommodations\n\nQualified individuals with known disabilities may be entitled to reasonable accommodation under the Americans with Disabilities Act and certain state or local laws.\n\nIf you need a reasonable accommodation for any part of the application process, please visit your nearest location or contact us at hrcompliance@basspro.com.\n\nFull Time Benefits Summary:\nEnjoy discounts on retail merchandise, our restaurants, world-class resorts and conservation attractions!\n• Medical\n• Dental\n• Vision\n• Health Savings Account\n• Flexible Spending Account\n• Voluntary benefits\n• 401k Retirement Savings\n• Paid holidays\n• Paid vacation\n• Paid sick time\n• Bass Pro Cares Fund\n• And more!\n\nBass Pro Shops is an equal opportunity employer. Hiring decisions are administered without regard to race, color, creed, religion, sex, pregnancy, sexual orientation, gender identity, age, national origin, ancestry, citizenship status, disability, veteran status, genetic information, or any other basis protected by applicable federal, state or local law.\n\nReasonable Accommodations\n\nQualified individuals with known disabilities may be entitled to reasonable accommodation under the Americans with Disabilities Act and certain state or local laws.\nIf you need a reasonable accommodation for any part of the application process, please visit your nearest location or contact us at hrcompliance@basspro.com.\nBass Pro Shops",
    "job_is_remote": false,
    "job_posted_at_timestamp": 1646179200,
    "job_posted_at_datetime_utc": "2022-03-02T00:00:00.000Z",
    "job_city": "Springfield",
    "job_state": "MO",
    "job_country": "US",
    "job_latitude": 37.208958,
    "job_longitude": -93.2923,
    "job_benefits": [
        "paid_time_off",
        "health_insurance",
        "retirement_savings"
    ],
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=pF4M_gBZl9kAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": null,
    "job_offer_expiration_timestamp": null,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 36,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": [
        "Dev Team",
        "React",
        "CSS3",
        "Gulp.js",
        "Web Technologies",
        "javascript es6",
        "Angular",
        "svn",
        "Redux",
        "Object Oriented Design",
        "HTML",
        "API",
        "Jira",
        "Webpack",
        "cs fundamentals",
        "SCSS",
        "Web Accessibility",
        "Grunt",
        "Confluence",
        "Sass",
        "TypeScript",
        "Atlassian",
        "Git",
        "Compiler",
        "Bootstrap",
        "Code Management",
        "Agile Framework",
        "Templates",
        "Data Structures",
        "Bitbucket",
        "Team Lead - Algorithm Development & Performance Optimization",
        "Senior Engineer - Kafka",
        "Spark",
        "Hadoop",
        "React",
        "NoSQL",
        "Lead Engineer - React & React Native & javascript",
        "Open Source Java Developer - Hazelcast & Cassandra",
        "Interactive Developer - HTML & CSS & Javascript",
        "Back-End Java Engineer - Spring & Hibernate & Restful APIs",
        "Senior UI Developer - Javascript & Html & Css & Silverlight & Adobe Flex & Flash",
        "Magento Developer - Magento & PHP & Relational Databases - MySQL",
        "Freelancer Web Design & Development & Search Engine Optimization",
        "Front End Developer - React.js & Backbone.js & Javascript & Node.Js"
    ],
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": true,
        "degree_preferred": true,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": null,
    "job_max_salary": null,
    "job_salary_currency": null,
    "job_salary_period": null,
    "job_highlights": {
        "Qualifications": [
            "3+ years hands-on experience in developing and minimum 2 years’ experience with React or other JS based technologies",
            "BS degree in Computer Science or related field",
            "Solid understanding of web technologies, including HTML, CSS3, and JavaScript",
            "Ability to integrate 3rd party APIs and a strong understanding of REST and other API patterns",
            "Experience working on NodeJS, ReactJS, Angular, Bootstrap, Typescript",
            "Experience with state management like Redux, React-Context, Recoil or similar library",
            "Knowledge on JavaScript ES6 features such as classes, arrow functions, string templates, rest/spread operators, promises, async/await",
            "Familiar with building responsive layouts using CSS and its compiler workflows (e.g. LESS, SASS/SCSS, styled components)",
            "Strong understanding of CS fundamentals, Object Oriented Design and Data Structures",
            "Strong troubleshooting and problem-solving skills, strong interpersonal, verbal, and written communication skills, strong relationship builder in cross-functional teams",
            "Experience building, optimizing, and maintaining websites with high traffic and performance demands",
            "Familiarity using SVN/GIT/Bitbucket for source code management and Atlassian tools Jira and Confluence"
        ],
        "Responsibilities": [
            "Frontend React Developer will be a member of Digital Commerce team responsible for developing and supporting eCommerce capabilities on multiple brand websites",
            "As part of a dynamic team with growing demand, this role will be responsible for requirement gathering, developing & testing website related enhancements, as well as troubleshooting and remediating issues within the application",
            "This includes support for end-to-end application testing, understanding of integrations to upstream/downstream systems, and adhering to code management activities within an agile framework",
            "This role will work with on/offshore dev team members in supporting and delivering solutions"
        ],
        "Benefits": [
            "Vision",
            "Health Savings Account",
            "Flexible Spending Account",
            "Voluntary benefits",
            "401k Retirement Savings",
            "Paid holidays",
            "Paid vacation",
            "Paid sick time",
            "Bass Pro Cares Fund"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3",
    "job_occupational_categories": [
        "Base Camp HQ"
    ],
    "job_naics_code": "44832",
    "job_naics_name": "Luggage and Leather Goods Stores"
  },
  {
    "employer_name": "Software Guidance & Assistance, Inc. (SGA, Inc.)",
    "employer_logo": "https://cdn.filestackcontent.com/nIZ0kkB5T5ur8klq3qgp",
    "employer_website": "http://www.sgainc.com",
    "employer_company_type": null,
    "job_publisher": "LinkedIn",
    "job_id": "W1QOc_MKofcAAAAAAAAAAA==",
    "job_employment_type": "CONTRACTOR",
    "job_title": "Remote Java/React Developer",
    "job_apply_link": "https://www.linkedin.com/jobs/view/remote-java-react-developer-at-software-guidance-assistance-inc-sga-inc-3639944050",
    "job_apply_is_direct": false,
    "job_apply_quality_score": 0.5846,
    "job_description": "Software Guidance & Assistance, Inc., (SGA), is searching for a Remote Java/ React Developer for a CONTRACT assignment with one of our premier Healthcare Services clients in Jacksonville, FL.\n\nResponsibilities :\n• Responsible for the development, programming, and coding of Information Technology solutions using ReactJS, Redux, D3 and NodeJS to enable Customer Experience applications.\n• Responsible for documenting detailed system specifications, participation in unit testing and maintenance of planned and unplanned internally developed applications, evaluation and performance testing of purchased products.\n• Responsible for including IT Controls to protect the confidentiality, integrity, as well as availability of the application and data processed or output by the application.\n• Lead efforts, oversee work results, provide training and serve as a technical resource for other Developers.\n\nRequired Skills:\n• Bachelor's Degree in Computer Science or Mathematics or relevant work experience\n• 5-8 years of IT development/programming/coding professional work experience\n• Proficiency programming in an object-oriented programming language: Java\n• Proficiency working in Springboot framework\n• Proficiency programming in React.JS, Node.JS, JavaScript, and HTML\n• Solid knowledge of React and Redux principals and build out\n• Proficiency with Oracle PL/SQL Packages Procedures\n• Solid knowledge of DOM manipulation and client-side validation\n• Experience with modern web/UI development tools and techniques: Node, Webpack, Axios, Jest\n• Source Control / Continuous Integration: GIT\n• Experience with unit testing, release procedures, coding design and documentation protocol as well as change management procedures\n• Proficiency using MERN and MEAN Scaffolding tools\n• Demonstrated organizational, analytical and interpersonal skills\n• Flexible team player\n• Ability to manage tasks independently and take ownership of responsibilities\n• Ability to learn from mistakes and apply constructive feedback to improve performance\n• Must demonstrate initiative and effective independent decision-making skills\n• Ability to communicate technical information clearly and articulately\n• Ability to adapt to a rapidly changing environment\n• In-depth understanding of the systems development life cycle\n• Proficiency programming in more than one object-oriented programming language; React.Js, Node.JS, JavaScript, and HTML\n• Proficiency with HTML, CSS, SASS, JavaScript/jQuery, local storage, and cross-browser compatibility are required\n• May include database knowledge in MongoBD\n• Experience with modern web/UI development tools and techniques: Node, Webpack, Grunt/Gulp, GIT, Axios, Jest\n• Client-side templating: mustache.js, handlebars.js, panni.js, and dust.js\n• Proficiency using standard desktop applications such as MS Suite and flowcharting tools such as Visio\n• Proficiency using debugging tools such as; Advanced Debugger, Allinea DDT, AQtime, ARM, CA/EZTEST, etc\n• Solid knowledge of DOM manipulation and client-side validation\n• Solid knowledge with jQuery and other JavaScript libraries\n• High critical thinking skills to evaluate alternatives and present solutions that are consistent with business objectives and strategy\n• Experience with responsive grid systems\n• Solid knowledge of React and Redux principals and build out\nPreferred Skills:\n• Various Domain experience; Health Care, Financial, etc\n• Experience using Agile, Waterfall, or hybrid methodology\n• Experience with mobile design (native and mobile web) a plus\n• Experience with Foundation a plus\n• Experience with web accessibility guidelines and requirements a plus\n• Relevant Development certifications A PLUS\n• DevOps\nSGA is a technology and resource solutions provider driven to stand out. We are a women-owned business. Our mission: to solve big IT problems with a more personal, boutique approach. Each year, we match consultants like you to more than 1,000 engagements. When we say let's work better together, we mean it. You'll join a diverse team built on these core values: customer service, employee development, and quality and integrity in everything we do. Be yourself, love what you do and find your passion at work. Please find us at https://sgainc.com .\n\nEEO Employer: Race, Color, Sex, Sexual Orientation, Gender Identity, Religion, National Origin, Disability, Veteran Status, Age, Marital Status, Pregnancy, Genetic Information, or Other Legally Protected Status.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687541572,
    "job_posted_at_datetime_utc": "2023-06-23T17:32:52.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=W1QOc_MKofcAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": "2023-12-23T12:41:02.000Z",
    "job_offer_expiration_timestamp": 1703335262,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": true
    },
    "job_required_skills": null,
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": true,
        "degree_preferred": true,
        "professional_certification_mentioned": true
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": null,
    "job_max_salary": null,
    "job_salary_currency": null,
    "job_salary_period": null,
    "job_highlights": {
        "Qualifications": [
            "Bachelor's Degree in Computer Science or Mathematics or relevant work experience",
            "5-8 years of IT development/programming/coding professional work experience",
            "Proficiency working in Springboot framework",
            "Solid knowledge of React and Redux principals and build out",
            "Proficiency with Oracle PL/SQL Packages Procedures",
            "Solid knowledge of DOM manipulation and client-side validation",
            "Source Control / Continuous Integration: GIT",
            "Experience with unit testing, release procedures, coding design and documentation protocol as well as change management procedures",
            "Proficiency using MERN and MEAN Scaffolding tools",
            "Demonstrated organizational, analytical and interpersonal skills",
            "Flexible team player",
            "Ability to manage tasks independently and take ownership of responsibilities",
            "Ability to learn from mistakes and apply constructive feedback to improve performance",
            "Must demonstrate initiative and effective independent decision-making skills",
            "Ability to communicate technical information clearly and articulately",
            "Ability to adapt to a rapidly changing environment",
            "In-depth understanding of the systems development life cycle",
            "Proficiency programming in more than one object-oriented programming language; React.Js, Node.JS, JavaScript, and HTML",
            "Proficiency with HTML, CSS, SASS, JavaScript/jQuery, local storage, and cross-browser compatibility are required",
            "May include database knowledge in MongoBD",
            "Experience with modern web/UI development tools and techniques: Node, Webpack, Grunt/Gulp, GIT, Axios, Jest",
            "Client-side templating: mustache.js, handlebars.js, panni.js, and dust.js",
            "Proficiency using standard desktop applications such as MS Suite and flowcharting tools such as Visio",
            "Proficiency using debugging tools such as; Advanced Debugger, Allinea DDT, AQtime, ARM, CA/EZTEST, etc",
            "Solid knowledge with jQuery and other JavaScript libraries",
            "High critical thinking skills to evaluate alternatives and present solutions that are consistent with business objectives and strategy",
            "Experience with responsive grid systems"
        ],
        "Responsibilities": [
            "Responsible for the development, programming, and coding of Information Technology solutions using ReactJS, Redux, D3 and NodeJS to enable Customer Experience applications",
            "Responsible for documenting detailed system specifications, participation in unit testing and maintenance of planned and unplanned internally developed applications, evaluation and performance testing of purchased products",
            "Responsible for including IT Controls to protect the confidentiality, integrity, as well as availability of the application and data processed or output by the application",
            "Lead efforts, oversee work results, provide training and serve as a technical resource for other Developers"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3"
  },
  {
    "employer_name": "Upwork",
    "employer_logo": "https://image.status.io/z6aeO6kAGsAG.png",
    "employer_website": "http://www.elance.com",
    "employer_company_type": "Computer Services",
    "job_publisher": "Upwork",
    "job_id": "j5lW-wffuhIAAAAAAAAAAA==",
    "job_employment_type": "CONTRACTOR",
    "job_title": "React Developer for E- Commerce Frontend (MVP)",
    "job_apply_link": "https://www.upwork.com/freelance-jobs/apply/React-Developer-for-Commerce-Frontend-MVP_~01c881a3216d1922e0/",
    "job_apply_is_direct": true,
    "job_apply_quality_score": 0.6813,
    "job_description": "We are seeking a skilled React.js Developer to build a simple e-commerce frontend (MVP) for our rapidly growing business. The ideal candidate should have experience building dynamic web applications using the latest technologies and a strong passion for web development.\n\nResponsibilities:\n\n-Develop a responsive ,user friendly e-commerce website using ReactJS.\n\n-Design and implement product listings,shopping cart functionality,and a simple checkout process.\n\n-Write reusable ,testable and efficient code.\n\n-Collaborate with our backend team to intergrate RESTful APIs.\n\n- Use your understanding of core web principles to recommed and help implement best practices for website performances ,scalability, and usability.\n\n-Collaborate with the design team to ensure the technical feasibility of UI/UX designs.\n\n-Continuously learn and keep upto date with emerging technologies to evaluate impact on business and member value.\n\nRequired Skills:\n\n-React.js,JavaScript,Typescript\n\n-HTML5, CSS3 ,Tailwind CSS\n\n-JSON,Stripe,Webpack,Babel,NPL\n\nDesired:\n\n-Experience with with e-commerce platforms\n\n- Familiarity with payment gateway integration.\n\nThis project is an excellent opportunity for motivated individual who is eager to make an impact. If you have the right skills and are upto the challenge,we would love to hear from you.\n\nThis is an MVP stage ,and if things are going well ,this will be a permanent role.",
    "job_is_remote": true,
    "job_posted_at_timestamp": 1687811969,
    "job_posted_at_datetime_utc": "2023-06-26T20:39:29.000Z",
    "job_city": null,
    "job_state": null,
    "job_country": "US",
    "job_latitude": 37.09024,
    "job_longitude": -95.71289,
    "job_benefits": null,
    "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=j5lW-wffuhIAAAAAAAAAAA%3D%3D",
    "job_offer_expiration_datetime_utc": null,
    "job_offer_expiration_timestamp": null,
    "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
    },
    "job_required_skills": [
        "Tailwind CSS",
        "Redux",
        "webpack",
        "HTML5",
        "TypeScript",
        "React",
        "Stripe"
    ],
    "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
    },
    "job_experience_in_place_of_education": false,
    "job_min_salary": null,
    "job_max_salary": null,
    "job_salary_currency": null,
    "job_salary_period": null,
    "job_highlights": {
        "Qualifications": [
            "The ideal candidate should have experience building dynamic web applications using the latest technologies and a strong passion for web development",
            "React.js,JavaScript,Typescript",
            "HTML5, CSS3 ,Tailwind CSS",
            "JSON,Stripe,Webpack,Babel,NPL"
        ],
        "Responsibilities": [
            "Develop a responsive ,user friendly e-commerce website using ReactJS",
            "Design and implement product listings,shopping cart functionality,and a simple checkout process",
            "Write reusable ,testable and efficient code",
            "Collaborate with our backend team to intergrate RESTful APIs",
            "Use your understanding of core web principles to recommed and help implement best practices for website performances ,scalability, and usability",
            "Collaborate with the design team to ensure the technical feasibility of UI/UX designs",
            "Continuously learn and keep upto date with emerging technologies to evaluate impact on business and member value"
        ]
    },
    "job_job_title": null,
    "job_posting_language": "en",
    "job_onet_soc": "15113400",
    "job_onet_job_zone": "3",
    "job_naics_code": "541511",
    "job_naics_name": "Custom Computer Programming Services"
  }
]